CREATE TABLE PESSOA_TABLE (
  ID_PESSOA NUMERIC(10) NOT NULL ,
  PRIMEIRO_NOME VARCHAR(25) NOT NULL,
  SOBRE_NOME VARCHAR(50) NULL,
  DATA_NASCIMENTO DATE NULL,
  SEXO CHAR(1) NULL,
  CPF VARCHAR(15) NOT NULL,
  NUMERO_CELULAR VARCHAR(15) NOT NULL,
  EMAIL VARCHAR(100) NULL
);

ALTER TABLE PESSOA_TABLE ADD CONSTRAINT PESSOA_PK PRIMARY KEY (ID_PESSOA);

CREATE TABLE CLIENTE_TABLE (
  ID_CLIENTE NUMERIC(10) NOT NULL,
  ID_PESSOA NUMERIC(10) NOT NULL,
  BANDEIRA_CARTAO VARCHAR(25) NULL,
  NUMERO_CARTAO NUMERIC(25) NULL
);

ALTER TABLE CLIENTE_TABLE ADD CONSTRAINT CLIENTE_PK PRIMARY KEY (ID_CLIENTE);

ALTER TABLE CLIENTE_TABLE ADD CONSTRAINT CLIENTE_FK FOREIGN KEY (ID_PESSOA) REFERENCES PESSOA_TABLE (ID_PESSOA);

CREATE TABLE MOTORISTA_TABLE (
  ID_MOTORISTA NUMERIC(10) NOT NULL,
  ID_PESSOA NUMERIC(10) NOT NULL,
  DATA_CADASTRO DATE NOT NULL,
  STATUS_MOTORISTA CHAR(1) NOT NULL,
  CARTEIRA_MOTORISTA VARCHAR(12) NOT NULL
);

ALTER TABLE MOTORISTA_TABLE ADD CONSTRAINT MOT_PK PRIMARY KEY (ID_MOTORISTA);

ALTER TABLE MOTORISTA_TABLE ADD CONSTRAINT MOTX_FK FOREIGN KEY (ID_PESSOA) REFERENCES PESSOA_TABLE (ID_PESSOA);

CREATE TABLE VEICULO_TABLE (
  ID_VEICULO NUMERIC(10) NOT NULL ,
  ID_MOTORISTA NUMERIC(10) NOT NULL,
  PLACA_VEICULO VARCHAR(8) NOT NULL,
  MODELO_VEICULO VARCHAR(25) NULL,
  MARCA_VEICULO VARCHAR(25) NULL,
  COR_VEICULO VARCHAR(25) NULL,
  ACENTOS_VEICULO NUMERIC(2) NOT NULL
);

ALTER TABLE VEICULO_TABLE ADD CONSTRAINT VEICULO_PK PRIMARY KEY (ID_VEICULO);

ALTER TABLE VEICULO_TABLE ADD CONSTRAINT VEICULO_FK FOREIGN KEY (ID_MOTORISTA) REFERENCES MOTORISTA_TABLE (ID_MOTORISTA);

CREATE TABLE VIAGEM_TABLE (
  ID_VIAGEM NUMERIC(10) NOT NULL ,
  ID_VEICULO NUMERIC(10) NOT NULL,
  ID_MOTORISTA NUMERIC(10) NOT NULL,
  ID_CLIENTE NUMERIC(10) NOT NULL,
  ENDERECO_SAIDA VARCHAR(100) NOT NULL,
  ENDERECO_CHEGADA VARCHAR(100) NOT NULL,
  DATA_INICIO DATE NOT NULL,
  DATA_FIM DATE NOT NULL
);

ALTER TABLE VIAGEM_TABLE ADD CONSTRAINT VIAGEM_PK PRIMARY KEY (ID_VIAGEM);

ALTER TABLE VIAGEM_TABLE ADD CONSTRAINT VIA_VEI_FK FOREIGN KEY (ID_VEICULO) REFERENCES VEICULO_TABLE (ID_VEICULO);

ALTER TABLE VIAGEM_TABLE ADD CONSTRAINT VIA_MOT_FK FOREIGN KEY (ID_MOTORISTA) REFERENCES MOTORISTA_TABLE (ID_MOTORISTA);

ALTER TABLE VIAGEM_TABLE ADD CONSTRAINT VIA_CLI_FK FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE_TABLE (ID_CLIENTE);

CREATE SEQUENCE CLIENTE_SEQUENCE 
MINVALUE 1
MAXVALUE 100000
INCREMENT BY 1
START WITH 1;

CREATE SEQUENCE PESSOA_SEQUENCE 
MINVALUE 1
MAXVALUE 100000
INCREMENT BY 1
START WITH 1;

CREATE SEQUENCE MOTORISTA_SEQUENCE 
MINVALUE 1
MAXVALUE 100000
INCREMENT BY 1
START WITH 1;

CREATE SEQUENCE VIAGEM_SEQUENCE 
MINVALUE 1
MAXVALUE 100000
INCREMENT BY 1
START WITH 1;

CREATE SEQUENCE VEICULO_SEQUENCE 
MINVALUE 1
MAXVALUE 100000
INCREMENT BY 1
START WITH 1;

