DROP TABLE VIAGEM_TABLE;

DROP TABLE CLIENTE_TABLE;

DROP TABLE VEICULO_TABLE;

DROP TABLE MOTORISTA_TABLE;

DROP TABLE PESSOA_TABLE;



DROP SEQUENCE PESSOA_SEQUENCE;

DROP SEQUENCE CLIENTE_SEQUENCE;

DROP SEQUENCE MOTORISTA_SEQUENCE;

DROP SEQUENCE VEICULO_SEQUENCE;

DROP SEQUENCE VIAGEM_SEQUENCE;
