SELECT * FROM  PESSOA_TABLE P INNER JOIN MOTORISTA_TABLE M
ON P.ID_PESSOA = M.ID_PESSOA
WHERE UPPER(PRIMEIRO_NOME) || ' ' || UPPER(SOBRE_NOME) LIKE '%IL%';

SELECT * FROM  PESSOA_TABLE P INNER JOIN CLIENTE_TABLE C
ON P.ID_PESSOA = C.ID_PESSOA
WHERE UPPER(PRIMEIRO_NOME) || ' ' || UPPER(SOBRE_NOME) LIKE '%A%';

SELECT * FROM PESSOA_TABLE
WHERE UPPER(PRIMEIRO_NOME) || ' ' || UPPER(SOBRE_NOME) LIKE '%A%';

SELECT * FROM VEICULO_TABLE
WHERE UPPER(MODELO_VEICULO) LIKE '%G%';


SELECT * FROM VIAGEM_TABLE
WHERE UPPER(ENDERECO_SAIDA) || ' ' || UPPER(ENDERECO_CHEGADA) LIKE '%CURITIBA%';